# Binaries
brew "git"
brew "git-lfs"
brew "jq"
brew "mtr"
brew "syncthing"
brew "tmux"

# App casks
cask "appcleaner"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "gpg-suite"
cask "iterm2"
cask "jetbrains-toolbox"
cask "slack"
cask "spotify"
cask "the-unarchiver"
cask "vagrant"
cask "virtualbox"
cask "virtualbox-extension-pack"
